apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-hpa
  namespace: hello-ns
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hello-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50  