apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-configmap
  namespace: hello-ns
data:
  index.html: |
    <html>
    <h1>Welcome!</h1>
    </br>
    <h1>Greetings from Hello Service!</h1>
    </html>